export const audioAssets: Record<string, {
  url: string,
  group: string,
}> = {
  bgm_title: { url: '/assets/audios/bgm_title.mp3', group: 'bgm' },
  bgm_mainmenu: { url: '/assets/audios/bgm_mainmenu.mp3', group: 'bgm'},
  bgm_settings: { url: '/assets/audios/bgm_settings.mp3', group: 'bgm'},
  bgm_battlemenu: { url: '/assets/audios/bgm_battlemenu.mp3', group: 'bgm'},
  bgm_character: {url: '/assets/audios/bgm_character.mp3', group: 'bgm'},
  bgm_stage: {url: '/assets/audios/bgm_stage.mp3', group: 'bgm'},
  bgm_mission: {url: '/assets/audios/bgm_mission.mp3', group: 'bgm'},
  bgm_shop: {url: '/assets/audios/bgm_shop.mp3', group: 'bgm'},
  bgm_stage1: { url: '/assets/audios/bgm_stage1.mp3', group: 'bgm'},
  sfx_confirm: { url: '/assets/audios/sfx_confirm.mp3', group: 'sfx' },
  sfx_cancel: { url: '/assets/audios/sfx_cancel.mp3', group: 'sfx' },
  sfx_explosion: { url: '/assets/audios/sfx_explosion.mp3', group: 'sfx' },
  sfx_hurt: { url: '/assets/audios/sfx_hurt.mp3', group: 'sfx' },
  sfx_coin: { url: '/assets/audios/sfx_coin.mp3', group: 'sfx' },
  sfx_aliceAttack: { url: '/assets/audios/sfx_aliceAttack.mp3', group: 'sfx' },
  sfx_yuutaAttack: { url: '/assets/audios/sfx_yuutaAttack.mp3', group: 'sfx' },
  sfx_aliceWalk: { url: '/assets/audios/sfx_aliceWalk.mp3', group: 'sfx' },
  sfx_yuutaWalk: { url: '/assets/audios/sfx_yuutaWalk.mp3', group: 'sfx' },
  sfx_countdown: { url: '/assets/audios/sfx_countdown.mp3', group: 'sfx' },
  sfx_countdownFinish: { url: '/assets/audios/sfx_countdownFinish.mp3', group: 'sfx' },
};