export const imageAssets: Record<string, string> = {
  splashScreenLogo: '/assets/images/splashScreenLogo.webp',
  gameLogo: '/assets/images/gameLogo.webp',
  banner01: '/assets/images/banner01.webp',
  banner02: '/assets/images/banner02.webp',
  backgroundWhite: '/assets/images/backgroundWhite.webp',
  backgroundWhiteButton: '/assets/images/backgroundWhiteButton.webp',
  characterBackground: '/assets/images/characterBackground.webp',
  stageBackground: '/assets/images/stageBackground.webp',
  stage01background: '/assets/images/stage01background.webp',
  yuutaPortrait: '/assets/images/characters/yuuta/yuutaPortrait.webp',
  alicePortrait: '/assets/images/characters/alice/alicePortrait.webp',
  // Game character sprites
  yuutaRun: '/assets/images/characters/yuuta/yuutaRun.webp',
  yuutaJump: '/assets/images/characters/yuuta/yuutaJump.webp',
  yuutaAttack: '/assets/images/characters/yuuta/yuutaAttack.webp',
  yuutaAttackEffect: '/assets/images/characters/yuuta/yuutaAttackEffect.webp',
  aliceRun: '/assets/images/characters/alice/aliceRun.webp',
  aliceJump: '/assets/images/characters/alice/aliceJump.webp',
  aliceAttack: '/assets/images/characters/alice/aliceAttack.webp',
  aliceAttackEffect: '/assets/images/characters/alice/aliceAttackEffect.webp',
  // Game objects
  enemy: '/assets/images/enemy.webp',
  coin: '/assets/images/coin.webp',
  trap: '/assets/images/trap.webp',
  explosion: '/assets/images/explosion.webp',
};